export const ADD_INGREDIENTS = "ADD_INGREDIENT";
export const REMOVE_INGREDIENTS = "REMOVE_INGREDIENT";
export const SET_INGREDIENTS = 'SET_INGREDIENTS';

export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCAHSE_BURGER_SUCCESS = 'PURCAHSE_BURGER_SUCCESS';
export const PURCAHSE_BURGER_FAIL = 'PURCAHSE_BURGER_FAIL';

export const FETCH_ORDERS_START = 'FETCH_ORDERS_START';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAIL = 'FETCH_ORDERS_FAIL';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';